# 2.1: Matrix Operations

## Notes

## Exercises

In [2]:
# Setup
import torch 

**Problem: Produce the following matrices (without keying in each entry of the matrix)**

a. A 4 x 5 matrix of zeros

In [3]:
# matrix size 
shape = (4,5,)
# matrix of zeros using the shape
zeros_tensor = torch.zeros(shape)
# display above matrix
print("Zeros Tensor: \n {}".format(zeros_tensor))

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


b. A 5 x 3 matrix of ones

In [4]:
# matrix size
shape = (5,3,)
# matrix of ones using the shape
ones_tensor = torch.ones(shape)
# display matrix
print("Ones Tensor: \n {}".format(ones_tensor))

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


c. The 5 x 5 identity matrix

Method: Filling pivot positions of the matrix with value 1

In [21]:
# matrix size
shape = (5,5,)
# pivot value
pivot = 1
# make a zero matrix
zeros_tensor = torch.zeros(shape)
# pivot positions in identity matrix must be ones
identity_tensor = zeros_tensor.fill_diagonal_(pivot)
# display identity matrix
print("Identity Tensor: \n {}".format(identity_tensor))

Identity Tensor: 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


Method: Provide a vector of ones to torch.diag or torch.diagflat

In [22]:
# size
vector_size = 5
# make a vector
ones_vector = torch.ones(vector_size)
# create the identity matrix
id_tensor_1 = torch.diag(ones_vector)
# display identity matrix
print("Identity Tensor 1: \n {}".format(id_tensor_1))
# create 2nd identity matrix
id_tensor_2 = torch.diagflat(ones_vector)
# display 2nd matrix
print("Identity Tensor 2: \n {}".format(id_tensor_2))

Identity Tensor 1: 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Identity Tensor 2: 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


d. A 4 x 4 diagonal matrix, with diagonal entries 3, 4, 2, 5

   Between two methods discovered above, it is better to use 2nd method for different entries on our diagonal.

In [27]:
# matrix size
shape = (4,4,)
# vector data
data = [3, 4, 2, 5]
# make a vector
vector = torch.tensor(data)
# create diagonal matrix with desired entries
diag_matrix = torch.diag(vector)
# display matrix
print("Diagonal Matrix: \n {}".format(diag_matrix))

Diagonal Matrix: 
 tensor([[3, 0, 0, 0],
        [0, 4, 0, 0],
        [0, 0, 2, 0],
        [0, 0, 0, 5]])


**Observation**: A useful way to test new ideas in matrix algebra, or to make conjectures,  is to make calculations with matrices selected at random.

**Problem: Create a 5 x 6 matrix with random entries**

In [30]:
# tensor shape
shape = (5,6,)
# create tensor with random entries
rand_tensor = torch.rand(shape)
# display
print("Random Tensor: \n {}".format(rand_tensor))
print("Tensor Size: {}".format(rand_tensor.shape))
print("Tensor Data Type: {}".format(rand_tensor.dtype))
print("Device Tensor Is Stored On: {}".format(rand_tensor.device))

Random Tensor: 
 tensor([[0.3721, 0.3003, 0.2537, 0.9327, 0.8904, 0.2613],
        [0.2015, 0.5203, 0.8707, 0.9034, 0.3224, 0.0402],
        [0.1862, 0.7260, 0.7008, 0.9567, 0.9470, 0.4316],
        [0.1110, 0.8372, 0.5519, 0.6201, 0.4774, 0.9666],
        [0.8372, 0.2464, 0.4884, 0.0901, 0.4593, 0.6614]])
Tensor Size: torch.Size([5, 6])
Tensor Data Type: torch.float32
Device Tensor Is Stored On: cpu


Create a 4 x 4 matrix with random integers entries between -9 and 9

In [35]:
# tensor shape
shape = (4,4,)
# create tensor with random integers
int_tensor = torch.randint(-9, 9, shape)
# display
print(f"Random Integer Tensor: \n {int_tensor}")
# Find the largest value in tensor
print(f"Largest value: {torch.max(int_tensor)}")

Random Integer Tensor: 
 tensor([[ 8, -9, -3, -1],
        [ 7, -8,  5, -7],
        [ 7,  4, -3, -7],
        [-4, -3,  0, -1]])
Largest value: 8


**Problem: Construct a random 4 x 4 matrices A & B to test whether AB = BA**

Test 4 pairs of random 4 x 4 matrices

In [51]:
# matrix size
shape = (4,4,)
# number of tensors
num_tensors = 4

# 2 batches of tensors
batch_1 = []
batch_2 = []
# create  matrices
for _ in range(num_tensors):
    rand_tensor_1 = torch.randint(9, shape)
    batch_1.append(rand_tensor_1)
    rand_tensor_2 = torch.randint(9, shape)
    batch_2.append(rand_tensor_2)
    
for A, B in zip(batch_1, batch_2):
    # matrix multiplication: calculate AB 
    output = torch.matmul(A, B)
    # calculate BA
    output_2 = torch.matmul(B, A)
    # verify the hypothesis AB = BA
    desired_zeros_mtrx = torch.sub(output, output_2) 
    # display
    print(f"AB = \n {output} \nBA = \n {output_2} \nSupposed Zeros Matrix = \n {desired_zeros_mtrx}")
    

AB = 
 tensor([[ 96,  90,  70, 119],
        [105, 108,  76, 128],
        [ 46,  55,  58,  65],
        [ 40,  43,  48,  56]]) 
BA = 
 tensor([[ 49,  71,  62,  78],
        [ 51,  88,  65,  87],
        [ 56,  84,  91, 105],
        [ 26, 110,  62,  90]]) 
Supposed Zeros Matrix = 
 tensor([[ 47,  19,   8,  41],
        [ 54,  20,  11,  41],
        [-10, -29, -33, -40],
        [ 14, -67, -14, -34]])
AB = 
 tensor([[ 66,  81,  54,  39],
        [ 71,  88,  85,  77],
        [ 81, 101,  95,  78],
        [ 77, 131, 123,  88]]) 
BA = 
 tensor([[ 57, 134,  53, 134],
        [ 21,  70,  41,  54],
        [ 42, 108,  60,  97],
        [ 90, 160,  88, 150]]) 
Supposed Zeros Matrix = 
 tensor([[  9, -53,   1, -95],
        [ 50,  18,  44,  23],
        [ 39,  -7,  35, -19],
        [-13, -29,  35, -62]])
AB = 
 tensor([[86, 81, 39, 39],
        [48, 75, 65, 23],
        [46, 94, 94, 18],
        [24, 35, 25,  9]]) 
BA = 
 tensor([[ 87,  32,  58,  45],
        [ 56,  49,  57,  17],
        [ 

Our hypothesis is that AB = BA; however, based on calculations for 4 pairs of random matrices, we clearly see that this is not the case for every pair of matrices because the result matrix is not a zeros matrix in all four examples. Thus, AB is not equal to BA.

**Problem: Given matrix $S$ below, compute $S^{k}$ for $k = 2,\dots,6$**

In [53]:
# matrix S
shape = (5,5,) # size of matrix S
v_size = 4 # size of vector
vector = torch.ones(v_size) # create the vector
S = torch.diagflat(vector, 1) # 2nd argument is offset, which determines which diagonal to fill values in
print(f"Matrix S: \n {S}") # display matrix S
current_computation = torch.diagflat(vector, 1) # similar to S, but this tensor will store final computation
# Compute S^k
for k in range(5): # Computing from S^2 to S^6 takes 5 times
    torch.matmul(current_computation, S, out=current_computation)
    print(f"S^{k+2} = \n {current_computation}")

Matrix S: 
 tensor([[0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.]])
S^2 = 
 tensor([[0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
S^3 = 
 tensor([[0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
S^4 = 
 tensor([[0., 0., 0., 0., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
S^5 = 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
S^6 = 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
