# 2.1: Matrix Operations

## Notes

## Exercises

In [2]:
# Setup
import torch 

Produce the following matrices (without keying in each entry of the matrix)

a. A 4 x 5 matrix of zeros

In [3]:
# matrix size 
shape = (4,5,)
# matrix of zeros using the shape
zeros_tensor = torch.zeros(shape)
# display above matrix
print("Zeros Tensor: \n {}".format(zeros_tensor))

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


b. A 5 x 3 matrix of ones

In [4]:
# matrix size
shape = (5,3,)
# matrix of ones using the shape
ones_tensor = torch.ones(shape)
# display matrix
print("Ones Tensor: \n {}".format(ones_tensor))

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


c. The 5 x 5 identity matrix

Method: Filling pivot positions of the matrix with value 1

In [21]:
# matrix size
shape = (5,5,)
# pivot value
pivot = 1
# make a zero matrix
zeros_tensor = torch.zeros(shape)
# pivot positions in identity matrix must be ones
identity_tensor = zeros_tensor.fill_diagonal_(pivot)
# display identity matrix
print("Identity Tensor: \n {}".format(identity_tensor))

Identity Tensor: 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


Method: Provide a vector of ones to torch.diag or torch.diagflat

In [22]:
# size
vector_size = 5
# make a vector
ones_vector = torch.ones(vector_size)
# create the identity matrix
id_tensor_1 = torch.diag(ones_vector)
# display identity matrix
print("Identity Tensor 1: \n {}".format(id_tensor_1))
# create 2nd identity matrix
id_tensor_2 = torch.diagflat(ones_vector)
# display 2nd matrix
print("Identity Tensor 2: \n {}".format(id_tensor_2))

Identity Tensor 1: 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Identity Tensor 2: 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


d. A 4 x 4 diagonal matrix, with diagonal entries 3, 4, 2, 5

   Between two methods discovered above, it is better to use 2nd method for different entries on our diagonal.

In [25]:
# matrix size
shape = (4,4,)
# make a vector
vector = torch.tensor([3,4,2,5])
# create diagonal matrix with desired entries
diag_matrix = torch.diag(vector)
# display matrix
print("Diagonal Matrix: \n {}".format(diag_matrix))

Diagonal Matrix: 
 tensor([[3, 0, 0, 0],
        [0, 4, 0, 0],
        [0, 0, 2, 0],
        [0, 0, 0, 5]])
