# 2.1: Matrix Operations

## Notes

## Exercises

In [2]:
# Setup
import torch 

**Problem: Produce the following matrices (without keying in each entry of the matrix)**

a. A 4 x 5 matrix of zeros

In [3]:
# matrix size 
shape = (4,5,)
# matrix of zeros using the shape
zeros_tensor = torch.zeros(shape)
# display above matrix
print("Zeros Tensor: \n {}".format(zeros_tensor))

Zeros Tensor: 
 tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


b. A 5 x 3 matrix of ones

In [4]:
# matrix size
shape = (5,3,)
# matrix of ones using the shape
ones_tensor = torch.ones(shape)
# display matrix
print("Ones Tensor: \n {}".format(ones_tensor))

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


c. The 5 x 5 identity matrix

Method: Filling pivot positions of the matrix with value 1

In [21]:
# matrix size
shape = (5,5,)
# pivot value
pivot = 1
# make a zero matrix
zeros_tensor = torch.zeros(shape)
# pivot positions in identity matrix must be ones
identity_tensor = zeros_tensor.fill_diagonal_(pivot)
# display identity matrix
print("Identity Tensor: \n {}".format(identity_tensor))

Identity Tensor: 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


Method: Provide a vector of ones to torch.diag or torch.diagflat

In [22]:
# size
vector_size = 5
# make a vector
ones_vector = torch.ones(vector_size)
# create the identity matrix
id_tensor_1 = torch.diag(ones_vector)
# display identity matrix
print("Identity Tensor 1: \n {}".format(id_tensor_1))
# create 2nd identity matrix
id_tensor_2 = torch.diagflat(ones_vector)
# display 2nd matrix
print("Identity Tensor 2: \n {}".format(id_tensor_2))

Identity Tensor 1: 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
Identity Tensor 2: 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


d. A 4 x 4 diagonal matrix, with diagonal entries 3, 4, 2, 5

   Between two methods discovered above, it is better to use 2nd method for different entries on our diagonal.

In [27]:
# matrix size
shape = (4,4,)
# vector data
data = [3, 4, 2, 5]
# make a vector
vector = torch.tensor(data)
# create diagonal matrix with desired entries
diag_matrix = torch.diag(vector)
# display matrix
print("Diagonal Matrix: \n {}".format(diag_matrix))

Diagonal Matrix: 
 tensor([[3, 0, 0, 0],
        [0, 4, 0, 0],
        [0, 0, 2, 0],
        [0, 0, 0, 5]])


**Observation**: A useful way to test new ideas in matrix algebra, or to make conjectures,  is to make calculations with matrices selected at random.

**Problem: Create a 5 x 6 matrix with random entries**

In [30]:
# tensor shape
shape = (5,6,)
# create tensor with random entries
rand_tensor = torch.rand(shape)
# display
print("Random Tensor: \n {}".format(rand_tensor))
print("Tensor Size: {}".format(rand_tensor.shape))
print("Tensor Data Type: {}".format(rand_tensor.dtype))
print("Device Tensor Is Stored On: {}".format(rand_tensor.device))

Random Tensor: 
 tensor([[0.3721, 0.3003, 0.2537, 0.9327, 0.8904, 0.2613],
        [0.2015, 0.5203, 0.8707, 0.9034, 0.3224, 0.0402],
        [0.1862, 0.7260, 0.7008, 0.9567, 0.9470, 0.4316],
        [0.1110, 0.8372, 0.5519, 0.6201, 0.4774, 0.9666],
        [0.8372, 0.2464, 0.4884, 0.0901, 0.4593, 0.6614]])
Tensor Size: torch.Size([5, 6])
Tensor Data Type: torch.float32
Device Tensor Is Stored On: cpu


Create a 4 x 4 matrix with random integers entries between -9 and 9

In [35]:
# tensor shape
shape = (4,4,)
# create tensor with random integers
int_tensor = torch.randint(-9, 9, shape)
# display
print(f"Random Integer Tensor: \n {int_tensor}")
# Find the largest value in tensor
print(f"Largest value: {torch.max(int_tensor)}")

Random Integer Tensor: 
 tensor([[ 8, -9, -3, -1],
        [ 7, -8,  5, -7],
        [ 7,  4, -3, -7],
        [-4, -3,  0, -1]])
Largest value: 8


**Problem: Construct a random 4 x 4 matrices A & B to test whether AB = BA**

Test 4 pairs of random 4 x 4 matrices

In [47]:
# matrix size
shape = (4,4,)
# number of tensors
num_tensors = 4

# 2 batches of tensors
batch_1 = []
batch_2 = []
# create  matrices
for _ in range(num_tensors):
    rand_tensor_1 = torch.randint(9, shape)
    batch_1.append(rand_tensor_1)
    rand_tensor_2 = torch.randint(9, shape)
    batch_2.append(rand_tensor_2)
    
for A, B in zip(batch_1, batch_2):
    # matrix multiplication
    output = torch.matmul(A, B)
    # display
    print(f"AB = {output}")

AB = tensor([[ 20,  28,  12,   0],
        [ 98,  91,  32,  79],
        [112, 130,  49,  92],
        [ 87,  98,  32,  79]])
AB = tensor([[ 85, 134,  69,  66],
        [ 84, 108,  70,  48],
        [ 90, 158,  81,  90],
        [ 60,  84,  44,  36]])
AB = tensor([[ 80,  88, 114,  87],
        [ 12,  35,  29,  30],
        [ 72, 101, 103, 116],
        [ 33,  68,  70,  67]])
AB = tensor([[ 77,  16,  62,  62],
        [ 68,  11,  39,  66],
        [ 84,  17,  55,  77],
        [112,  28,  64, 114]])
